// ============================================================
// Mock Data for Local Development
// Used when the headhunter API is not available
// ============================================================

import type { Consultant, Job } from "./types";

export const MOCK_CONSULTANT: Consultant = {
  uid: "jacky",
  displayName: "Jacky Chen",
  email: "jacky@step1ne.com",
  role: "ADMIN",
  contactPhone: "0912-345-678",
  contactEmail: "jacky@step1ne.com",
  lineId: "jacky_step1ne",
  telegramHandle: "jacky_step1ne",
  siteConfig: {
    slug: "jacky",
    template: "minimal",
    primaryColor: "#1a1a1a",
    accentColor: "#3b82f6",
    heroTitle: "找到適合你的職涯下一步",
    heroSubtitle:
      "專注科技產業獵才超過 8 年，協助上千位人才找到理想工作。讓我用專業與熱情，為你的職涯加速。",
    avatar: "",
    bio: "擁有 8 年以上科技產業獵才經驗，專精於軟體工程、產品管理、AI/ML 領域。\n\n曾協助多家知名科技公司（包括新創與上市企業）成功招募關鍵人才。深信每位人才都值得找到最適合的舞台。\n\n我的服務理念：透明溝通、專業媒合、長期陪伴。不只是幫你找工作，更要幫你找到職涯的最佳路徑。",
    specialties: ["軟體工程", "產品管理", "AI/ML", "新創", "FinTech"],
    yearsExperience: 8,
    socialLinks: {
      email: "jacky@step1ne.com",
      phone: "0912-345-678",
      linkedin: "https://linkedin.com/in/jacky-step1ne",
      line: "jacky_step1ne",
    },
    seoTitle: "Jacky Chen - Step1ne 獵頭顧問",
    seoDescription: "專注科技產業獵才，協助你找到職涯下一步",
    featuredJobIds: [1, 2, 3],
    testimonials: [
      {
        name: "王小明",
        role: "Senior Engineer @ TechCorp",
        content:
          "Jacky 非常專業且耐心，不只幫我找到理想的工作，還在薪資談判上給了很大的幫助。非常推薦！",
      },
      {
        name: "李小華",
        role: "Product Manager @ StartupX",
        content:
          "第一次透過獵頭找工作，Jacky 讓整個過程非常順暢。他對產業的了解讓媒合精準度很高。",
      },
    ],
    isPublished: true,
  },
};

export const MOCK_JOBS: Job[] = [
  {
    id: 1,
    position_name: "Senior Frontend Engineer",
    client_company: "TechCorp Inc.",
    department: "Engineering",
    salary_range: "120-180 萬/年",
    key_skills: "React, TypeScript, Next.js, Tailwind CSS, GraphQL",
    job_description:
      "負責公司核心產品的前端架構設計與開發，帶領 3-5 人的前端團隊。",
    job_status: "招募中",
    industry: "科技",
    location: "台北市",
    interview_process: "HR 電話 → 技術面試 → Team Lead 面試 → CTO 面試",
    consultant: "Jacky Chen",
    education_requirement: "大學以上",
    experience_requirement: "5年以上",
    language_requirement: "英文中上",
    remote_policy: "混合辦公（每週2天遠端）",
    headcount: 2,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: 2,
    position_name: "Backend Engineer (Node.js)",
    client_company: "FinTech Solutions",
    salary_range: "100-150 萬/年",
    key_skills: "Node.js, PostgreSQL, Redis, Docker, AWS, TypeScript",
    job_description: "開發與維護金融科技平台的後端微服務架構。",
    job_status: "招募中",
    industry: "金融",
    location: "台北市",
    interview_process: "HR 電話 → 線上 Coding Test → 技術面試 → VP 面試",
    consultant: "Jacky Chen",
    experience_requirement: "3年以上",
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: 3,
    position_name: "AI/ML Engineer",
    client_company: "AI Startup Lab",
    salary_range: "130-200 萬/年",
    key_skills: "Python, PyTorch, TensorFlow, NLP, LLM, RAG",
    job_description: "負責 LLM 應用開發與模型微調，建構企業級 AI 解決方案。",
    job_status: "招募中",
    industry: "科技",
    location: "台北市",
    interview_process: "HR 電話 → Technical Challenge → 技術面試 → CEO 面試",
    consultant: "Jacky Chen",
    experience_requirement: "3年以上",
    remote_policy: "全遠端",
    created_at: "2026-03-08T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: 4,
    position_name: "Product Manager",
    client_company: "E-Commerce Giant",
    salary_range: "100-160 萬/年",
    key_skills: "產品規劃, 數據分析, Agile, SQL, Figma",
    job_description: "負責電商平台核心功能的產品策略與路線圖規劃。",
    job_status: "招募中",
    industry: "電商",
    location: "新北市",
    interview_process: "HR 電話 → Case Study → PM Lead 面試 → 總經理面試",
    consultant: "Jacky Chen",
    experience_requirement: "5年以上",
    created_at: "2026-03-02T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: 5,
    position_name: "DevOps Engineer",
    client_company: "Cloud Native Corp",
    salary_range: "110-170 萬/年",
    key_skills: "Kubernetes, Docker, AWS, Terraform, CI/CD, Linux",
    job_description: "建構與維護雲端基礎設施，推動 DevOps 文化轉型。",
    job_status: "招募中",
    industry: "科技",
    location: "台北市",
    interview_process: "HR 電話 → 技術面試 → Infra Lead 面試",
    consultant: "Jacky Chen",
    experience_requirement: "4年以上",
    remote_policy: "混合辦公",
    created_at: "2026-03-06T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
];
